from seleniumbase import BaseCase
BaseCase.main(__name__, __file__)


class RecorderTest(BaseCase):
    def test_recording(self):
        self.open("https://lucachak02.pythonanywhere.com/")
        self.click('a:contains("View All Services")')
        self.click('a:contains("Let\'s Work Together")')
        self.click('a:contains("Home")')
        self.open_if_not_url("https://lucachak02.pythonanywhere.com/")
        self.click('a:contains("Home")')
        self.open_if_not_url("https://lucachak02.pythonanywhere.com/")
        self.click("ul.link-list li:nth-of-type(2) a")
        self.open_if_not_url("https://lucachak02.pythonanywhere.com/services/")
        self.click("ul.link-list li:nth-of-type(3) a")
        self.open_if_not_url("https://lucachak02.pythonanywhere.com/Projects/")
        self.click("ul.link-list li:nth-of-type(4) a")
        self.open_if_not_url("https://lucachak02.pythonanywhere.com/about/")
        self.click("ul.link-list li:nth-of-type(5) a")
        self.open_if_not_url("https://lucachak02.pythonanywhere.com/contact/")
        self.click('a[href="/services/"]')
        self.open_if_not_url("https://lucachak02.pythonanywhere.com/services/")
        self.click('a[href="/Projects/"]')
        self.open_if_not_url("https://lucachak02.pythonanywhere.com/Projects/")
        self.click('a[href="/contact/"]')
        self.open_if_not_url("https://lucachak02.pythonanywhere.com/contact/")
        self.click('a[href="/coffee"]')
        self.click('img[alt="Homepage"]')
        self.open_if_not_url("https://lucachak02.pythonanywhere.com/")
        self.click('a:contains("More About Me")')
        self.open_if_not_url("https://lucachak02.pythonanywhere.com/about/")
        self.click('a[title="Back to Top"] svg')
        self.click('img[alt="Homepage"]')
        self.open_if_not_url("https://lucachak02.pythonanywhere.com/")
        self.click('a[href="/Projects/"]')
        self.open_if_not_url("https://github.com/lucachak/Crud_Django")
        self.click('a[href="/Projects/"]')
        self.open_if_not_url("https://lucachak02.pythonanywhere.com/Projects/")
        self.click('a[href="single.html"]')
        self.open_if_not_url("https://lucachak02.pythonanywhere.com/Projects/single.html")
